thesis.pdf: revision references.bib thesis.tex classicthesis-config.tex Chapters/**/*.tex FrontBackmatter/*.tex
	latexmk -recorder -pdf -pdflatex="pdflatex -shell-escape" --synctex=1 -use-make thesis

diff.pdf: references.bib diff.tex 
	latexmk -recorder -pdf -pdflatex="pdflatex -shell-escape" --synctex=1 -use-make diff

clean:
	rm -f *.lot *.lof *.lol *.toc *.log *.out *.aux *.blg *.bbl thesis.pdf Chapters/*.aux Chapters/**/*.aux frontback/*.aux

revision:
	echo '% Autogenerated, do not edit' > revision.tex
	echo "\\\newcommand{\\\revisiondate}{`git log -1 --format=\"%ad\" --date=short`}" >> revision.tex
	echo "\\\newcommand{\\\revision}{`git log -1 --format=\"%h\"`}" >> revision.tex

rebuild: clean thesis.pdf
